### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by FMassin** [VolcSAT/scdummyloc#1]
The module, while ran in command line for online processing or post-processing with input file, always ends with:
```bash
Segmentation fault (core dumped)
```
regardless of being interrupted with CRTL+c or just reaching the end of input file without being interrupted.

**Comment by FMassin** [comment]
Hello @gempa-jabe and @Luca-s

I hope this little module is simple enough and sufficiently [documented](https://scdummyloc.readthedocs.io) so you can get what's going in here :)

Any help with this issue? What is the correct way to implement proper module termination? 

Cheers

Fred

**Comment by gempa-jabe** [comment]
Run with gdb and make sure that all libraries are compatible.

**Comment by FMassin** [comment]
scdummyloc is just a one file python module, and I am not use to use how to use gdb with python. Could you please tell me more? Sorry.

**Comment by gempa-jabe** [comment]
Sorry, I can't spend my time with this one. You can run gdb with any binary and Python is a binary: `gdb --args python3 /path/to/script.py`.

**Comment by FMassin** [comment]
No problem, thanks, for the records, I had tried a few variations from the top of my mind and  the command you then suggested, but it did not work.

**Comment by FMassin** [comment]
Thanks @luca-s and  @gempa-jabe!
